
x-spark-worker-common:
  &spark-worker-common
  build: ./docker/spark/
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_HOME=/opt/bitnami/spark
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark
    - MINIO_URL=http://minio:9000    
  volumes:
    - ./data:/opt/bitnami/spark/data
  networks:
    - projeto_airflow_spark  
  depends_on:
    - spark-master

services:
  spark-master:
    build: ./docker/spark/   
    container_name: 'docker-spark-master'
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_MODE=master
      - SPARK_HOME=/opt/bitnami/spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no      
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_USER=spark
      - MINIO_URL=http://minio:9000
    ports:
      - '9090:8080'
      - '7077:7077'
      - '4040:4040'
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf
      - ./spark/app/src:/opt/bitnami/spark/app
      - ./spark/jars_dir:/opt/bitnami/spark/ivy
      - ./data:/opt/bitnami/spark/data
    networks:
    - projeto_airflow_spark
  spark-worker-1:
    container_name: 'docker-spark-worker-1'
    <<: *spark-worker-common
  spark-worker-2:
    container_name: 'docker-spark-worker-2'
    <<: *spark-worker-common
  minio:
    image: 'bitnami/minio:latest'
    container_name: 'docker-minio'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root12345
      - MINIO_URL=http://minio:9000
    # command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    networks:
      - projeto_airflow_spark
  jupyter:
    build: ./docker/jupyter
    container_name: 'docker-jupyter'
    ports:
      - "8888:8888"
    volumes:
      - ./spark/jupyter_scripts:/home/jovyan/work
    networks:
    - projeto_airflow_spark     

networks:
  projeto_airflow_spark:
    external: true

volumes:
  minio_storage:
    driver: local