
x-spark-worker-common:
  &spark-worker-common
  build: ./
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_HOME=/opt/bitnami/spark
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    # - SPARK_USER=${SPARK_UID}:${SPARK_GID}
  volumes:
    - ../data:/opt/bitnami/spark/data
  env_file: ../.env
  # user: "${SPARK_UID:-1000}:${SPARK_GID:-0}"
  depends_on:
    - spark-master

services:
  spark-master:
    build: ./   
    container_name: 'docker-spark-master'
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_MODE=master
      - SPARK_HOME=/opt/bitnami/spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      # - SPARK_USER=${SPARK_UID}:${SPARK_GID}
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    ports:
      - '9090:8080'
      - '7077:7077'
      - '4040:4040'
    volumes:
      - ./conf:/opt/bitnami/spark/conf
      - ./app/src:/opt/bitnami/spark/app
      - ./jars_dir:/opt/bitnami/spark/ivy
      - ../data:/opt/bitnami/spark/data
    env_file: ../.env
    # user: "${SPARK_UID:-1000}:${SPARK_GID:-0}"
  spark-worker-1:
    container_name: 'docker-spark-worker-1'
    <<: *spark-worker-common
  spark-worker-2:
    container_name: 'docker-spark-worker-2'
    <<: *spark-worker-common   
networks:
  default:
    name: cnefe
    external: false
# volumes:
#   data:
#     external: true
      